### ISSUE TITLE
GeometryProxy needs to extend GeoPHP's Geometry

### ISSUE THREAD

**Issue by abdelrahmankhedr** [spinen/laravel-geometry#15]
FatalThrowableError in Geometry.class.php line 273:
Type error: Argument 1 passed to Geometry::contains() must be an instance of Geometry, array given

```
$polygon = \App\Polygon::find(10);
    $point = Geo::parseWkt("POINT(46.7193603515625 24.780890141913442)");
    $geo =Geo::parseGeoJson($polygon->geojson);
     $result=$geo->contains($point);
    dd($result);
```

**Comment by ssfinney** [comment]
Hey @abdelrahmankhedr, thanks for the report! We'll take a look.

**Comment by ssfinney** [comment]
@abdelrahmankhedr I've looked at this, and found that our special `GeometryProxy` class is causing this issue since the `Point` class extends the proxy class, not the GeoPHP Geometry class.

I'll circle back to this later and see if we can find a solution, otherwise feel free to submit a PR.

**Comment by vegazrelli** [comment]
Any solution? It happens to me too :-(

**Comment by jellebreuer** [comment]
+1

**Comment by jimmypuckett** [comment]
@ssfinney I have been digging into this a bit, and I am not sure that I understand why you think that the proxy should extend the proxy.  If you look on [at line 113 of the proxy](https://github.com/spinen/laravel-geometry/blob/develop/src/Support/GeometryProxy.php#L113), then you see that if the method exist on the object being proxied, then we call it, so the `contains` on the object returned by `parseGeoJson` would be called.  Let's review this together on Monday & see if we cannot put this to bed...

**Comment by jimmypuckett** [comment]
@jbreuer95 Can you provide a short snippet of what you are doing to get the error?

Thanks.

**Comment by jellebreuer** [comment]
@jimmypuckett 
I use geoPHP directly now but it was something like this.

```
$path =  resource_path('data/'.$country.'.geo.json');
$space = Geo::parseGeoJson(file_get_contents($path));
$point = Geo::parseGeoJson('{ "type": "Point", "coordinates": ['.$lng.', '.$lat.'] }');

if ($space->contains($point)) {
```

**Comment by jimmypuckett** [comment]
@jbreuer95 I am sorry that we got so tied up & did not get this fixed.  Thanks for your quick response.

**Comment by jimmypuckett** [comment]
I have pushed up an initial draft of a solution.  I am not 100% sure that I like how the solution was implemented, but I know that was the problem.  I am going to go over with with @ssfinney tomorrow & then we will put out the official release.

For now, if any of you would like, you could us the `dev-feature/passGeometryObjectToGeoPhp` version to see if it addresses your issue.

Thanks again for everyone's time.

**Comment by jimmypuckett** [comment]
@ssfinney I just merged develop in with the different travis config.  After this builds, I am going to look into the way that we are doing this & see about adding test.  I will let you know when it is ready to review.

Thanks.

**Comment by jellebreuer** [comment]
Can anyone create a new version?

**Comment by jimmypuckett** [comment]
@jbreuer95 We just tagged version 0.6.0, which has this fix.

**Comment by jellebreuer** [comment]
@jimmypuckett Awesome!
