### ISSUE TITLE
how to `toWkb` as hex string ?

### ISSUE THREAD

**Issue by firodj** [spinen/laravel-geometry#24]
How to out `toWkb` as hex string as:
```
$wkb = new \WKB();
$wkb->write($point, TRUE);
```

**Comment by jimmypuckett** [comment]
This is a Laravel wrapper to geoPHP. Please reference their api here...

https://geophp.net/api.html

Thanks.

**Comment by firodj** [comment]
I need to pass an argument, but the proxy did not accept arguments, it call `out` function on geoPHP without argument.

https://github.com/spinen/laravel-geometry/blob/fe83a1c2ec04ef1d4c50f409c3c7d9fced5801e0/src/Support/GeometryProxy.php#L89

**Comment by jimmypuckett** [comment]
Sorry, did not understand request as your example code was directly calling the geoPHP package. 

Can you provide example using this package?
