### ISSUE TITLE
Laravel 7 support

### ISSUE THREAD

**Issue by hugo-lovighi** [spinen/laravel-geometry#28]
Hi @jimmypuckett !
Thank you for your work we use it a lot and we have to move to laravel 7 and php 7.4
Is it possible to have an laravel 7 update ? :)
illuminate/support not satisfiable

```
 Problem 1
    - Installation request for spinen/laravel-geometry ^2.2 -> satisfiable by spinen/laravel-geometry[2.2.0].
    - Conclusion: remove laravel/framework v7.2.0
    - Conclusion: don't install laravel/framework v7.2.0
    - illuminate/support v5.6.7 conflicts with laravel/framework[v7.2.0]
    .....
```

**Comment by jimmypuckett** [comment]
@kesm0 We have just pushed tag 2.3.0 with support.  Please let us know if you have any issues.

#29 & #30

**Comment by hugo-lovighi** [comment]
@jimmypuckett  Good job ! Thx
