### ISSUE TITLE
validating geometry is not working  

### ISSUE THREAD

**Issue by shweta199312** [spinen/laravel-geometry#43]
`include_once('../geoPHP.inc');

$json =
'{
"type": "FeatureCollection",
"name": "test_geopackage",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::32749" } },
"features": [
{ "type": "Feature", "properties": { "id": 1, "area": null }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ 493974.586960159242153, 9941492.856522602960467 ], [ 716836.730084917275235, 9948379.58891131542623 ], [ 723696.271854396560229, 9796114.265915364027023 ], [ 493977.325050417566672, 9799698.903731044381857 ], [ 493974.586960159242153, 9941492.856522602960467 ] ] ] ] } }
]
}
';

$multipoint1 = geoPHP::load($json, 'json');
echo "Area: ".$multipoint1->area()."<br>";
echo "Validity Result:".$multipoint1->checkValidity();`

I wanted to know if this code/API also have the function to read the invalid geometry, because it can calculate the polygons area, and how we can avoid to read the intersect polygons.

**Comment by jimmypuckett** [comment]
If you have a suggestion for what you would like to have fixed, please update us with your idea.
