### ISSUE TITLE
DI problems with Laravel 10

### ISSUE THREAD

**Issue by jellebean** [spinen/laravel-geometry#50]
Hey,

Thanks for your work on this repository, but there seems to be an issue when using it in Laravel 10.

The following code works in Laravel 9, but fails in Laravel 10:

```php
// ARRANGE
$geometry = $this->app->make(Geometry::class);
$polygonGeoJson = '{"type":"MultiPolygon","coordinates":[[[[4.2721668,51.3758503],[4.2798236,51.3761214],[4.2774246,51.3760352],[4.2774232,51.3760382],[4.2747282,51.3759419],[4.2721668,51.3758503]]]]}';

// ACT
$result = $geometry->parseGeoJson($polygonGeoJson);

$this->assertNotNull($result);
```

Proof: https://github.com/solvari/laravel-10-spinen-laravel-geo-issue/actions/runs/5463324635/jobs/9943867616

**Comment by nepda** [comment]
Yes, we have this too.

If you do a `app(Geometry::class, ['app' => null]);` it will work.

Otherwise, the Geometry classes will be resolved by the Service Container of Laravel and the specific classes (e.g. `Spinen\Geometry\Geometries\MultiPolygon`) cannot be instantiated.

**Comment by nepda** [comment]
@jellebean Is it possible for you, to run your tests with this branch to test it? I tested it locally with your code and it worked :)

**Comment by jellebean** [comment]
Hey @nepda, I'm no longer working at Solvari so I can't, but I'll pass the message along.

**Comment by jimmypuckett** [comment]
Version > 2.8 should address this. I don't have a project to test this with, but the PR @nepda made seems to address this, so I merged it.
